// src/data/categoriesData.js

const categories = [
  {
    id: 1,
    name: "Angkor Wat",
    detail: "Angkor Wat at Sunrise and Other Unforgettable Sights on an Asian Vacation.",
    image: "",
    image_url: "https://www.moon.com/wp-content/uploads/2018/12/iStock-504122496.jpg",
  },
  {
    id: 2,
    name: "Pub Street",
    detail: "Pub Street is a single street in Siem Reap that has many bars and restaurants.",
    image: "",
    image_url: "https://www.siemreap.net/wp-content/uploads/2018/01/pub-street-siem-reap-cambodia.jpg",
  },
  {
    id: 3,
    name: "Phnom Penh",
    detail: "Phnom Penh, the capital and largest city of Cambodia, is a vibrant metropolis situated at the confluence of the Tonle Sap, Mekong, and Bassac rivers.",
    image: "",
    image_url: "https://media.tacdn.com/media/attractions-splice-spp-674x446/06/6c/56/f8.jpg",
  },
  {
    id: 4,
    name: "Kep",
    detail: "Kep is a coastal province located in the southwestern part of Cambodia.",
    image: "",
    image_url: "https://d13jio720g7qcs.cloudfront.net/images/destinations/origin/5d80a2b6e2a9f.jpg",
  },
  {
    id: 5,
    name: "Royal Palace",
    detail: "Still the dwelling place of the king, this palace contains the Silver Pagoda, whose floor is made up of 5329 silver tiles.",
    image: "",
    image_url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/e4/ce/b1/20171006-093816-01-largejpg.jpg?w=1400&h=-1&s=1",
  },
  {
    id: 6,
    name: "Choeung Ek Genocidal Center",
    detail: "These were the execution grounds for the Khmer Rouge.",
    image: "",
    image_url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/76/7d/81/choeung-ek-genocidal.jpg?w=1000&h=800&s=1",
  },
  {
    id: 7,
    name: "Tuol Sleng Genocide Museum",
    detail: "The Tuol Sleng Genocide Museum is the memorial site of the S-21 detention center of the Khmer Rouge regime.",
    image: "",
    image_url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/81/d1/1e/barbed-wire.jpg?w=1000&h=800&s=1",
  },
  {
    id: 8,
    name: "Tonle Sap Lake",
    detail: "The largest freshwater lake in Southeast Asia, known for its floating villages and biodiversity.",
    image: "",
    image_url: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQ6fYwRGEsW6yxNBWHq_ePp2mT399jqzvmwUrVpoVoTeWYtHuCb5DL8WYxTNfpL2jghX5FLQKdEQvGpWkzSOYOrgu6NEq34KEXVWHuhRw",
  },
  {
    id: 9,
    name: "Bokor Hill Station",
    detail: "An abandoned French colonial resort town in Kampot with foggy mountain views.",
    image: "",
    image_url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/ec/68/e6/20180131-141211-2-largejpg.jpg?w=900&h=500&s=1",
  },
  {
    id: 10,
    name: "Battambang Bamboo Train",
    detail: "A unique bamboo platform on wheels powered by a small motor, offering a thrilling countryside ride.",
    image: "",
    image_url: "https://cms.siemreaper.click/uploads/bamboo_train_in_battambang2812_dc2ba95fa8.jpeg",
  },
  {
    id: 11,
    name: "Preah Vihear Temple",
    detail: "A UNESCO World Heritage Site located atop a 525-meter cliff in the Dângrêk Mountains.",
    image: "",
    image_url: "https://i0.wp.com/www.birdguideasso.org/wp-content/uploads/2018/09/Preah-Vihear-Temple-1-e1545105862913.jpg?fit=800%2C533&ssl=1",
  },
  {
    id: 12,
    name: "Koh Rong",
    detail: "An island paradise with white-sand beaches, turquoise waters, and vibrant marine life.",
    image: "",
    image_url: "https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcT6dpHQIxATrS3GEqszwJh9paA9uCpEgD0tSNjmLEnRInH-VzzU4SfXjzc_uP7eEtKTu9YAPeQDluV466WpSYcocZGW2pAUMUyIQOejEA",
  },
  {
    id: 13,
    name: "Kratie",
    detail: "A peaceful riverside town famous for sightings of rare Irrawaddy dolphins in the Mekong River.",
    image: "",
    image_url: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQ1R1usvjlHtnbtO8bk-kpSnmrNh1-Go-IHjheKm4M_ViH-WvmPdngGIUjFTkhonhvdD1tJd-X8QNDUNSQd5SDHotBTWss3OKUAa92Ucg",
  },
  {
    id: 14,
    name: "Ta Prohm Temple",
    detail: "Known for the massive tree roots that overgrow the ancient temple ruins, as seen in Tomb Raider.",
    image: "",
    image_url: "https://www.siemreap.net/wp-content/uploads/2016/11/Ta-Prohm-Temple.jpg",
  },
  {
    id: 15,
    name: "National Museum of Cambodia",
    detail: "Houses one of the world's largest collections of Khmer art and artifacts.",
    image: "",
    image_url: "https://lp-cms-production.imgix.net/2023-05/shutterstockRF135587363.jpg",
  },
  {
    id: 16,
    name: "Independence Monument",
    detail: "A landmark in Phnom Penh commemorating Cambodia's independence from France in 1953.",
    image: "",
    image_url: "https://www.greeneratravel.com/userfiles/850inde.jpg",
  },
  {
    id: 17,
    name: "Mondulkiri",
    detail: "A mountainous province with cool climate and waterfalls.",
    image: "",
    image_url: "https://kampatour.com/pic/blog/images/Mondulkiri-1.jpg",
  },
  {
    id: 18,
    name: "Ratanakiri",
    detail: "A remote province known for crater lakes and minority tribes.",
    image: "",
    image_url: "https://www.mondulkiriproject.org/wp-content/uploads/2019/06/Ratanakiri.jpg",
  },
  {
  id: 19,
  name: "Kratie",
  detail: "Famous for Irrawaddy dolphins and river views.",
  image: "",
  image_url: "https://authentiktravel.com/media/ckeditor/what%20to%20do%20in%20kratie%20colonial%20buildings.jpg",
},
{
  id: 20,
  name: "Kampong Thom",
  detail: "Known for ancient temples and archaeological sites.",
  image: "",
  image_url: "https://www.vivutravel.com/images/des-cambodia3/kampong-thom-travel-guide.jpg",
},
];

export default categories;
